[package]
name = "variables"
version = "0.1.0"
authors = ["sjsilves"]
edition = "2018"

[dependencies]
rayon = "1.0"
rand = "0.6.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[profile.release]
debug = true